version: '3'

services:
  django-app:
    container_name: notes
    build: ./Notes
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./env_variables/notes.env
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./env_variables/postgres.env
    volumes:
      - postgres_db_data:/var/lib/postgresql/data


volumes:
  postgres_db_data:

  